version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: porygon
    ports:
      - "3306:3306"
    networks:
      - porygon_network

networks:
  porygon_network:
    driver: bridge